# Generated by Django 4.2.2 on 2023-07-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MumChaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posting_date',
            new_name='post_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
